# Generated by Django 4.1 on 2023-01-06 07:22
import os
from django.contrib.auth.models import User
from django.db import migrations


def generate_superuser(apps, schema_editor):
    User.objects.create_superuser(
        username=os.environ.get('DJANGO_SU_NAME'),
        email=os.environ.get('DJANGO_SU_EMAIL'),
        password=os.environ.get('DJANGO_SU_PASSWORD')
    )


class Migration(migrations.Migration):
    dependencies = []
    operations = [
        migrations.RunPython(generate_superuser),
    ]
