# Generated by Django 4.1 on 2023-01-06 08:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='contained_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=1000), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
